content: |-
  # ALZ.LandingZones.Apps

  ## Overview

  This Terraform repository uses the internal `Terraform.LandingZones` module to provision Azure Subscriptions with some pre-configured defaults, such as:
  - A base Virtual Network (or multiple if desired) with a given CIDR range
  - A Service Principal and associated Connection within Azure DevOps for the provided project
  - A Terraform State bucket which can be used within Azure DevOps pipelines
  - An Azure DevOps Variable Group containing details for the Terraform State bucket and Subscription IDs

  **Note:** Within this repository, only **Application Subscriptions** (those which are intended for application services) should be defined. For **Platform Subscriptions**, use the `ALZ.LandingZones.Platform` repository.

  ## Updating Docs

  The `terraform-docs` utility is used to generate this README. Follow the below steps to update:
  1. Make changes to the `.terraform-docs.yml` file
  2. Fetch the `terraform-docs` binary (https://terraform-docs.io/user-guide/installation/)
  3. Run `terraform-docs markdown table --output-file ${PWD}/README.md --output-mode inject terraform/`

  ## Release Process

  The `Terraform.LandingZones` module is automatically tagged upon merge to the `main` branch. When a new version of the module is released, the `ALZ.LandingZones.Apps` repository should be updated to use the new version. This is done by updating the `source` parameter in the `main.tf` file to point to the new version.

  Any changes to Landing Zones should be performed on a feature branch and merged to the `main` branch once approved. The `main` branch is protected and requires at least one approval before merging. The below diagram shows the release process for an Application Landing Zone:

  ![apps](apps.png)

  ## Required Pipeline Variables

  The following variables are required to be set before running Terraform:
  - platform_environment: All Application Landing Zone environments (`dev`, `pre`, `prd`) are deployed to the **Prod** Azure Tenant.
  - core_storage_account_name: Read access is required to the Core Storage Account and the Terraform State within it. The State file contains the IDs for the Azure VWAN Hubs (provisioned by `ALZ.Connectivity`), which are required for connecting the Landing Zone to the Hub Network.
  - devops_org_name: The name of the Azure DevOps organisation all projects are located.
  - devops_pat: An Azure DevOps Personal Access Token for authentication.

  ## Landing Zone Variables

  The below code is an example of how to define an Application Landing Zone in the `main.tf` file.

  ```hcl
  {{ include "examples/main.tf" }}
  ```
